version: '3.7'
services:
  mysqldb:
    image: mysql:8
    ports:
      - '4449:3306'
    volumes:
      - ./myvolume:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

